install:
	cd /tmp && \
	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
	unzip -q awscliv2.zip && \
	sudo ./aws/install && \
	aws --version
	rm -rf /tmp/awscliv2.zip /tmp/aws