---
all:
  children:
    adm:
      hosts:
        adm1:
          ansible_host: 100.26.218.56
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    rproxy:
      hosts:
        rproxy1:
          ansible_host: 54.209.116.67
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    web:
      hosts:
        web1:
          ansible_host: 10.0.2.5
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@100.26.218.56 -i ../docs/admin.pem" -o StrictHostKeyChecking=no'
        web2:
          ansible_host: 10.0.3.5
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@100.26.218.56 -i ../docs/admin.pem" -o StrictHostKeyChecking=no'
        web3:
          ansible_host: 10.0.4.5
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@100.26.218.56 -i ../docs/admin.pem" -o StrictHostKeyChecking=no'
    
    db:
      hosts:
        db1:
          ansible_host: 10.0.5.5
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@100.26.218.56 -i ../docs/admin.pem" -o StrictHostKeyChecking=no'
    
    jenkins:
      hosts:
        jenkins1:
          ansible_host: 34.207.64.13
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    monitoring:
      hosts:
        prometheus1:
          ansible_host: 54.227.202.6
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        grafana1:
          ansible_host: 35.174.200.219
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../docs/admin.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    ansible_python_interpreter: /usr/bin/python3